### ISSUE TITLE
How are SRC / Simka / Commet (/ Compareads) related?

### ISSUE THREAD

**Issue by rchikhi** [GATB/rconnector#1]

**Comment by pierrepeterlongo** [comment]
Commet is an important update of compareads (new code, new IOs, binary operations between  results)
For the others: 

<img width="917" alt="screen shot 2016-06-29 at 16 06 02" src="https://cloud.githubusercontent.com/assets/8103041/16455093/6f033a9c-3e13-11e6-9184-6c87f8c0542d.png">
(with "scales up" meaning scaling up a project as large as the whole Tara ocean dataset for instance)

**Comment by rchikhi** [comment]
nice summary! what does "linked similarities" mean?

**Comment by genscale-admin** [comment]
"linked similarities" denotes the ability of the program to output the similar sequences. 
- Commet provides the similarity between a read and a read set. "This read (provided) is similar to at least one read (not provided) from this read set" 
  - SRC_linker provides the identifiers of similar reads. 
  - Simka does not provide any information about similar sequences, instead it provides measures.

**Comment by rchikhi** [comment]
i see! thanks for the clarification. 
I think you could call that "X-vs-Y similarity", with values being "read-vs-read similarity", "read-vs-dataset similarity" and "dataset-vs-dataset similarity", as you already did in the graphic.
